const name="hitesh";
const repocount=25;
// console.log(name+" " +repocount+" "+"12"+" "+"hello");
console.log(`hello my name is ${name}and my count is ${repocount}`);
console.log("hello"+"raj");
const gname=new String("rajat");
console.log(typeof(gname));
console.log(typeof(name));
console.log(gname[1]);
console.log(gname.length);
console.log(gname.toUpperCase());
console.log(gname.charAt(2));
console.log(gname.indexOf('a'));
console.log(gname.slice(0,3));
// console.log(gname.splice(1,2,"p"));
console.log(gname.substring(0,4));
const gname1=new String("   rajat     ")
console.log(gname1.trim());
const url="https://www.yoitube.com";
console.log(url.replace('y','-'));
console.log(url.includes('youtube'));
console.log(gname.split('-'));